### ISSUE TITLE
New empty file button

### ISSUE THREAD

**Issue by Sriram-bb63** [nanna7077/Luna#1]
**Describe the solution you'd like**
A "+" button near the tab to create a new empty file.

**Additional context**
I want a button to act like "ctrl+t" in web browser or "ctrl+n" in vscode.

**Comment by nanna7077** [comment]
Added in [commit 4cf722865f2fc61ff8161b51389240278d9f0fa2](https://github.com/nanna7077/Luna/commit/4cf722865f2fc61ff8161b51389240278d9f0fa2)

Thanks for the suggestion!
